export const caseStudyDB = [
  { id: 1, slug: 'nexus-bank', title: 'Fintech Scaling', client: 'Nexus Bank', impact: '+340% Conversions', desc: 'Rewriting a fragile legacy SPA into a robust Next.js App Router architecture, eliminating hydration errors and drastically improving SEO.', roi: 'Saved $2.4M in annual server operational costs by transitioning to Edge caching.' },
  { id: 2, slug: 'aura-store', title: 'Global E-Commerce', client: 'Aura Store', impact: '-80% Load Time', desc: 'Implemented edge caching, optimized image delivery, and aggressive static generation to ensure instant load times globally.', roi: 'Mobile checkout abandonment dropped by 45% within the first month.' },
  { id: 3, slug: 'caresync', title: 'Healthcare Portal', client: 'CareSync', impact: 'Zero Downtime', desc: 'Migrated monolithic infrastructure to decoupled microservices with strict HIPAA-compliant data layers.', roi: 'Improved patient onboarding speed by 60%, increasing clinic throughput.' },
  { id: 4, slug: 'metricflow', title: 'SaaS Dashboard', client: 'MetricFlow', impact: 'Sub-50ms TTFB', desc: 'Re-architected client-side heavy dashboards into Server Components, streaming data directly to the view.', roi: 'Enterprise retention increased by 15% due to improved perceived performance.', generated_by_ai: true },
  { id: 5, slug: 'lumina-tech', title: 'AI Integration', client: 'Lumina Tech', impact: '2.5x Engagement', desc: 'Embedded contextual AI models directly into the workflow using server-side Gemini API streams.', roi: 'User session length increased from 4 minutes to 11 minutes on average.', generated_by_ai: true },
  { id: 6, slug: 'freightx', title: 'Logistics Tracker', client: 'FreightX', impact: 'Real-time Sync', desc: 'Built a globally distributed WebSocket layer replacing legacy long-polling systems.', roi: 'Reduced dispatch errors by 92% saving $800k in misrouting.' },
  { id: 7, slug: 'learnsmart', title: 'EdTech Platform', client: 'LearnSmart', impact: '1M+ Concurrent', desc: 'Scaled the video delivery and interactive quiz modules using Next.js caching and CDN edge networks.', roi: 'Supported a 10x traffic spike during national exams flawlessly.' },
  { id: 8, slug: 'estatehub', title: 'PropTech CRM', client: 'EstateHub', impact: 'Automated Workflows', desc: 'Integrated robust headless CMS capabilities with dynamic routing for tens of thousands of properties.', roi: 'Agent listing time reduced from 2 hours to 15 minutes per property.' },
];
