#!/bin/bash
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/text-white/text-gray-900/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/bg-[#06080A]/bg-white/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/bg-[#090D15]/bg-gray-50/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/bg-[#0D111A]/bg-white/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/bg-[#131825]/bg-gray-50/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/text-gray-400/text-gray-600/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/text-gray-300/text-gray-700/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/border-white\/10/border-gray-200/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/border-white\/5/border-gray-100/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/bg-white\/5/bg-gray-100/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/bg-white\/10/bg-gray-200/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/text-[#D4FF00]/text-indigo-600/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/bg-[#D4FF00]/bg-indigo-600/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/border-[#D4FF00]/border-indigo-600/g'
find src -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/text-[#06080F]/text-white/g'
