const fs = require('fs');
let code = fs.readFileSync('src/pages/ProjectDetailPage.tsx', 'utf8');

const helmetImport = `import { Helmet } from 'react-helmet-async';`;
if (!code.includes('react-helmet-async')) {
    code = code.replace(`import SEOProvider from '../components/atoms/SEOProvider';`, `${helmetImport}\nimport SEOProvider from '../components/atoms/SEOProvider';`);
}

// Add JSON-LD and Blur header
const jsonLdTarget = `export default function ProjectDetailPage() {
  const { id } = useParams<{ id: string }>();
  const project = PROJECTS.find((p) => p.id === id);`;

const jsonLdCode = `
  const jsonLd = project ? {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": project.title,
    "image": [project.image],
    "datePublished": "2026-08-24T08:00:00+08:00",
    "author": [{
        "@type": "Organization",
        "name": "CHESTAADOTCOM"
    }],
    "publisher": {
      "@type": "Organization",
      "name": "CHESTAADOTCOM",
      "logo": {
        "@type": "ImageObject",
        "url": "https://chestaa.com/logo.png"
      }
    },
    "description": project.description,
    "about": {
      "@type": "Place",
      "name": "BSD City, Cisauk, Tangerang"
    }
  } : null;
`;
code = code.replace(jsonLdTarget, jsonLdTarget + jsonLdCode);

// Inject JSON-LD into the return structure
const returnTarget = `<main className="min-h-screen pt-24 pb-20 bg-slate-50 dark:bg-slate-900 transition-colors">`;
const returnReplacement = `<main className="min-h-screen bg-white dark:bg-slate-950 transition-colors">
      <Helmet>
         {jsonLd && <script type="application/ld+json">{JSON.stringify(jsonLd)}</script>}
      </Helmet>`;
code = code.replace(returnTarget, returnReplacement);

// Change Header to blurred parallax
const headerRegex = /<div className="bg-slate-900 text-white py-16 md:py-24">[\s\S]*?<\/div>\s*<\/div>\s*<\/div>/;
const parallaxHeader = `
      {/* Hero Section with Parallax Image */}
      <div className="relative h-[65vh] min-h-[500px] w-full overflow-hidden bg-black mb-16">
        <motion.div 
          className="absolute inset-0"
          initial={{ scale: 1.1 }}
          animate={{ scale: 1 }}
          transition={{ duration: 1.5, ease: 'easeOut' }}
        >
          <img 
            src={project.image} 
            alt={project.title}
            className="w-full h-full object-cover opacity-50"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-900/40 to-transparent" />
          <div className="absolute inset-0 backdrop-blur-sm" />
        </motion.div>

        <div className="absolute inset-0 flex items-end">
          <div className="max-w-4xl mx-auto px-6 pb-16 w-full">
            <Link to="/portfolio" className="inline-flex items-center gap-2 text-white/70 hover:text-white transition-colors mb-8 text-sm font-medium tracking-wide">
              <ArrowLeft size={16} /> BACK TO SHOWCASE
            </Link>
            
            <div className="flex flex-wrap items-center gap-3 mb-6">
              <span className="px-3 py-1 rounded-full bg-white/10 backdrop-blur-md border border-white/20 text-xs font-semibold text-white tracking-widest uppercase">
                  {project.category}
              </span>
              {project.id === 'ai-erp-dashboard' && ( // just an example condition for AI tag
                <span className="px-3 py-1 rounded-full bg-indigo-500/20 backdrop-blur-md border border-indigo-400/30 text-xs font-bold text-indigo-200 tracking-widest uppercase flex items-center gap-1.5">
                  <Zap size={12} className="text-indigo-400" /> GENERATED BY AI
                </span>
              )}
            </div>
            
            <h1 className="text-4xl md:text-5xl lg:text-7xl font-display font-medium text-white leading-[1.1] tracking-tight mb-6 drop-shadow-lg">
              {project.title}
            </h1>
            
            <p className="text-xl md:text-2xl text-white/80 font-serif max-w-3xl leading-relaxed">
               {project.description}
            </p>
          </div>
        </div>
      </div>
`;
code = code.replace(headerRegex, parallaxHeader);

// Adjust inner content typography
const innerContentTarget = `<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">`;
const innerContentReplacement = `<div className="max-w-4xl mx-auto px-6 lg:px-8">`;
code = code.replace(innerContentTarget, innerContentReplacement);

// Remove Breadcrumbs if exists since we added a back button
code = code.replace(/<Breadcrumbs[^>]*>/, '');

fs.writeFileSync('src/pages/ProjectDetailPage.tsx', code);
console.log('ProjectDetailPage patched.');
