import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
import { Home, ChevronRight, ArrowLeft, ArrowUpRight, Sparkles } from 'lucide-react';
import { caseStudyDB } from '../../../lib/caseStudies';
import { notFound } from 'next/navigation';
import SocialShare from '../../../components/molecules/SocialShare';

type Props = {
  params: Promise<{ slug: string }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const study = caseStudyDB.find(s => s.slug === slug);
  
  if (!study) {
    return {
      title: 'Case Study Not Found | chestaa.com',
    };
  }

  return {
    title: `${study.client}: ${study.title} | Case Studies | chestaa.com`,
    description: `Read how chestaa.com achieved ${study.impact} for ${study.client}. ${study.desc}`,
    openGraph: {
      title: `${study.client} - Enterprise ROI Case Study`,
      description: study.roi,
    }
  };
}

export async function generateStaticParams() {
  return caseStudyDB.map((study) => ({
    slug: study.slug,
  }));
}

export default async function CaseStudyPage({ params }: Props) {
  const { slug } = await params;
  const study = caseStudyDB.find(s => s.slug === slug);

  if (!study) {
    notFound();
  }

  const relatedStudies = caseStudyDB.filter(s => s.id !== study.id).slice(0, 3);

  return (
    <main className="relative min-h-screen flex flex-col items-center pb-20 overflow-hidden bg-slate-50 dark:bg-slate-950">
      <div className="w-full max-w-4xl mx-auto px-4 pt-48 md:pt-56 mb-12">
        
        {/* Breadcrumb for detail page */}
        <nav className="flex items-center gap-2 mb-12 text-sm font-medium text-slate-500 dark:text-slate-400 animate-in fade-in slide-in-from-top-8 duration-700">
          <Link href="/" className="hover:text-blue-600 dark:hover:text-blue-400 transition-colors flex items-center gap-1.5">
            <Home className="w-4 h-4" /> Home
          </Link>
          <ChevronRight className="w-4 h-4 text-slate-300 dark:text-slate-700" />
          <Link href="/case-studies" className="hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
            Case Studies
          </Link>
          <ChevronRight className="w-4 h-4 text-slate-300 dark:text-slate-700" />
          <span className="text-slate-900 dark:text-white truncate">{study.client}</span>
        </nav>

        <Link href="/case-studies" className="inline-flex items-center gap-2 text-blue-600 dark:text-blue-400 font-semibold mb-8 hover:opacity-80 transition-opacity animate-in fade-in slide-in-from-left-8 duration-700 delay-100 fill-mode-both">
          <ArrowLeft className="w-4 h-4" /> Back to all case studies
        </Link>

        <header className="animate-in fade-in slide-in-from-bottom-8 duration-1000 delay-200 fill-mode-both">
          <div className="flex flex-wrap items-center gap-3 mb-4">
            <p className="text-blue-600 dark:text-blue-400 font-bold tracking-widest uppercase text-sm">{study.client}</p>
            {/* @ts-ignore */}
            {study.generated_by_ai && (
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-500/10 dark:bg-blue-400/10 border border-blue-500/20 dark:border-blue-400/20 text-blue-600 dark:text-blue-400 text-xs font-bold tracking-widest uppercase backdrop-blur-md">
                <Sparkles className="w-3.5 h-3.5" /> Generated by AI
              </span>
            )}
          </div>
          <h1 className="text-4xl md:text-6xl font-bold tracking-tighter text-slate-900 dark:text-white mb-6">
            {study.title}
          </h1>
          <div className="mb-12">
            <SocialShare title={study.title} />
          </div>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16 animate-in fade-in slide-in-from-bottom-12 duration-1000 delay-300 fill-mode-both">
          <div className="md:col-span-2 prose prose-slate dark:prose-invert max-w-none prose-lg">
            <h3 className="text-2xl font-semibold mb-4 text-slate-900 dark:text-white">Project Overview</h3>
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-8">{study.desc}</p>
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
              Through rigorous architectural planning and execution, our Next.js App Router implementation 
              bypassed legacy limitations. By harnessing global edge caching, React Server Components, and 
              advanced asset optimization, we delivered an enterprise-grade digital experience that directly translates to business impact.
            </p>
          </div>
          <div className="bg-white/80 dark:bg-slate-900/80 backdrop-blur-3xl rounded-3xl p-8 border border-slate-200 dark:border-slate-800 shadow-xl h-max">
            <h3 className="text-xs uppercase tracking-widest font-bold text-slate-400 mb-6">Key Metrics</h3>
            <div className="mb-8">
              <p className="text-sm text-slate-500 dark:text-slate-400 font-medium mb-1">Architectural Impact</p>
              <p className="text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-emerald-500 to-blue-500">{study.impact}</p>
            </div>
            <div>
              <p className="text-sm text-slate-500 dark:text-slate-400 font-medium mb-2">Verified ROI</p>
              <p className="text-slate-900 dark:text-white font-medium leading-snug">{study.roi}</p>
            </div>
          </div>
        </div>

        {/* Related Case Studies Section */}
        <div className="mt-8 pt-16 border-t border-slate-200 dark:border-slate-800 animate-in fade-in slide-in-from-bottom-12 duration-1000 delay-500 fill-mode-both w-full relative">
          <h3 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white mb-8">Related Implementations</h3>
          
          <div className="flex overflow-x-auto gap-6 pb-8 snap-x snap-mandatory [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
            {relatedStudies.map((related) => (
              <Link
                key={related.id}
                href={`/case-studies/${related.slug}`}
                className="flex-shrink-0 w-[85%] md:w-[400px] snap-center bg-white/60 dark:bg-slate-900/60 backdrop-blur-3xl border border-slate-200/50 dark:border-slate-800 rounded-3xl p-8 hover:shadow-xl dark:hover:shadow-[0_8px_32px_rgba(0,0,0,0.4)] hover:-translate-y-1 transition-all duration-300 group relative flex flex-col justify-between h-[18rem]"
              >
                <div>
                  <div className="flex justify-between items-start mb-4">
                    <p className="text-xs font-semibold tracking-wider uppercase text-blue-600 dark:text-blue-400">{related.client}</p>
                    <ArrowUpRight className="w-5 h-5 text-slate-400 group-hover:text-blue-500 transition-colors" />
                  </div>
                  <h4 className="text-xl font-bold text-slate-900 dark:text-white mb-3">{related.title}</h4>
                  <p className="text-sm text-slate-600 dark:text-slate-400 line-clamp-3 mb-6 leading-relaxed">{related.desc}</p>
                </div>
                <div className="pt-4 border-t border-slate-200 dark:border-slate-800">
                  <p className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Impact</p>
                  <p className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-500 to-blue-500 font-bold">{related.impact}</p>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </div>
    </main>
  );
}
